GET http://localhost:8000/programa

###
GET http://localhost:8000/instructor

###

POST  http://localhost:8000/programa
Content-Type: application/json

{
    "nombre_programa":"ADSO"
}

###

PUT http://localhost:8000/programa
Content-Type: application/json

{
    "idprograma":"1",
    "nombre_programa":"Analisis y Desarrollo de Software"
}

###

DELETE http://localhost:8000/programa
Content-Type: application/json

{
    "idprograma":"8",
    "nombre_programa":""
}

###

POST  http://localhost:8000/aprendiz
Content-Type: application/json

{
    "nombres":"Luis",
    "apellidos":"Perez",
    "email":"Perez@gmail.com",
    "telefonos":"31187996"
}

###
PUT  http://localhost:8000/aprendiz
Content-Type: application/json

{
    "idaprendiz":"1",
    "nombres":"Luis",
    "apellidos":"Guezguan",
    "email":"luis@gmail.com",
    "telefonos":"3112824319"
}
###
GET http://localhost:8000/profesion
###
POST http://localhost:8000/profesion
Content-Type: application/json

{
    "nombre_profesion":"Maquinaria Pesada"
}
###
PUT http://localhost:8000/profesion
Content-Type: application/json

{
    "idprofesion":"7",
    "nombre_profesion":"Desarrollador y analisis"
}
###
DELETE http://localhost:8000/profesion
Content-Type: application/json
{
  "idprofesion": "7"
}

###
POST http://localhost:8000/ficha-aprendiz
Content-Type: application/json

{
  "ficha_idficha": 1,
  "aprendiz_idaprendiz": 2,
  "instructor_idinstructor": 2
}
###

DELETE  http://localhost:8000/ficha-aprendiz
Content-Type: application/json

{
  "ficha_idficha": 1,
  "aprendiz_idaprendiz": 2
  
}

###

POST http://localhost:8000/instructor
Content-Type: application/json

{
  "nombre": "Gustavo ",
  "apellido": "Jimenez",
  "email": "gimenez@gmail.com",
  "telefono":"3221993829"
}

###

GET http://localhost:8000/ficha-aprendiz

###

PUT http://localhost:8000/instructor
Content-Type: application/json

{
  "idinstructor":"2",
  "nombre":"julian",
  "apellido":"angarita",
  "email":"julian@gmail.com",
  "telefono":"3124569871"
}

###

DELETE http://localhost:8000/instructor
Content-Type: application/json

{
  "idinstructor":"2",
  "nombre":"",
  "apellido":"",
  "email":"",
  "telefono":""
}