POST  http://localhost:8000/aprendiz
Content-Type: application/json

{
    "nombres":"Luis",
    "apellidos":"Salamanca",
    "email":"luis@gmail.com",
    "telefonos":"3112824319"
}

###
PUT  http://localhost:8000/aprendiz
Content-Type: application/json

{
    "idaprendiz":"1",
    "nombres":"Luis",
    "apellidos":"Guezguan",
    "email":"luis@gmail.com",
    "telefonos":"3112824319"
}
###
GET http://localhost:8000/profesion
###
POST http://localhost:8000/profesion
Content-Type: application/json

{
    "nombre_profesion":"HSQ"
}
###
PUT http://localhost:8000/profesion
Content-Type: application/json

{
    "idprofesion":"5",
    "nombre_profesion":"Desarrollador"
}
###
DELETE http://localhost:8000/profesion
Content-Type: application/json

{
    "idprofesion":"5"
}